In [1]:
import numpy as np

a = np.random.randn(5)
a

array([-0.87557146, -1.42882878, -0.53887072,  1.47402041,  0.360092  ])

In [2]:
print(a.shape)
## this is called a rank 1 array in Python and
# it's neither a row vector nor a column vector

(5,)


In [3]:
a.T

array([-0.87557146, -1.42882878, -0.53887072,  1.47402041,  0.360092  ])

In [4]:
a.T.shape

(5,)

In [5]:
np.dot(a,a.T)

5.400961136138882

not a matrix but a value

So please reshape or do (5,1) to define the shape

And int his data struture,there are two square bracket when we print a transpose,Whereas previously,there was one square bracket.

In [6]:
a = np.random.randn(5,1)
a

array([[ 0.09837514],
       [ 0.47096518],
       [-0.68343937],
       [ 0.50410364],
       [ 2.13930911]])

In [7]:
a[1]

array([0.47096518])

In [10]:
b = np.random.randn(1,5)
b

array([[ 0.58740866, -0.7339807 , -0.98665197,  0.97646357,  0.2442286 ]])

In [9]:
a+b

array([[-0.03288553,  0.59525621,  0.61757962,  2.20452193, -1.00859925],
       [ 0.33970451,  0.96784624,  0.99016965,  2.57711196, -0.63600921],
       [-0.81470004, -0.18655831, -0.16423489,  1.42270742, -1.79041376],
       [ 0.37284297,  1.00098471,  1.02330812,  2.61025043, -0.60287075],
       [ 2.00804844,  2.63619017,  2.65851359,  4.2454559 ,  1.03233472]])

In [11]:
b+a

array([[ 0.6857838 , -0.63560556, -0.88827682,  1.07483871,  0.34260375],
       [ 1.05837384, -0.26301553, -0.51568679,  1.44742875,  0.71519378],
       [-0.09603071, -1.41742007, -1.67009134,  0.2930242 , -0.43921076],
       [ 1.09151231, -0.22987706, -0.48254832,  1.48056721,  0.74833225],
       [ 2.72671777,  1.4053284 ,  1.15265714,  3.11577268,  2.38353771]])