In [52]:
import torch,tensorflow
torch.__version__

'1.12.1+cpu'

## 基本使用方法
创建一个矩阵，据说比tensorflow简单很多

In [16]:
x = torch.empty(5,3)
x

tensor([[5.1429e-39, 4.5000e-39, 5.2347e-39],
        [5.2347e-39, 8.4489e-39, 9.6428e-39],
        [1.1112e-38, 9.5511e-39, 1.0102e-38],
        [1.0286e-38, 1.0194e-38, 9.6429e-39],
        [9.2755e-39, 9.1837e-39, 9.3674e-39]])

In [8]:
import numpy as np
import pandas as pd
x_np = np.empty([5,3])
x_np

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
x_np1 = np.zeros([5,3])
x_np1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

来一个随机数来试试水,tensor 是一个张量，二维叫矩阵

In [19]:
x = torch.rand(5,3)
x

tensor([[0.1091, 0.7173, 0.3245],
        [0.2319, 0.5067, 0.6826],
        [0.2206, 0.0643, 0.4273],
        [0.1335, 0.2803, 0.3185],
        [0.0323, 0.9938, 0.1871]])

初始化一个全零的矩阵

In [21]:
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

直接传入数据

In [22]:
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [23]:
x.shape

torch.Size([2])

我们可以感受到，与Numpy的区别并不大，其实这些框架的基本操作都是大同小异的

In [26]:
x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [32]:
x = torch.ones(5,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [33]:
x = torch.randn_like(x,dtype=torch.float)
x

tensor([[-0.8964, -0.3301, -0.8376],
        [ 0.1141, -1.0874, -3.1072],
        [-0.9953,  0.5045, -1.2474],
        [-0.7841, -0.5508,  0.0314],
        [-0.0146,  0.3559,  0.9869]])

tensor的大小

In [29]:
x.size()

torch.Size([5, 3])

In [30]:
x.shape

torch.Size([5, 3])

## 基本计算方法

In [34]:
y = torch.rand(5,3)
y

tensor([[0.2348, 0.8159, 0.6876],
        [0.5583, 0.7157, 0.8947],
        [0.3275, 0.1251, 0.5320],
        [0.4966, 0.1109, 0.1229],
        [0.7965, 0.5767, 0.6841]])

In [35]:
x+y

tensor([[-0.6617,  0.4858, -0.1500],
        [ 0.6724, -0.3717, -2.2125],
        [-0.6679,  0.6296, -0.7154],
        [-0.2875, -0.4399,  0.1544],
        [ 0.7819,  0.9325,  1.6710]])

In [37]:
torch.add(x,y)## 一样也是加法

tensor([[-0.6617,  0.4858, -0.1500],
        [ 0.6724, -0.3717, -2.2125],
        [-0.6679,  0.6296, -0.7154],
        [-0.2875, -0.4399,  0.1544],
        [ 0.7819,  0.9325,  1.6710]])

## 索引

In [38]:
x[:,1]

tensor([-0.3301, -1.0874,  0.5045, -0.5508,  0.3559])

## view操作可以改变矩阵的维度
可以对比reshape操作

In [39]:
x = torch.randn(4,4)
x

tensor([[ 0.2305, -0.4287, -0.1051, -1.8061],
        [-0.5696,  2.0598,  0.3050, -0.1690],
        [ 0.5868, -0.2422, -0.6184, -0.8001],
        [-0.4490, -0.2485,  0.5354, -1.5804]])

In [40]:
y = x.view(16)
y

tensor([ 0.2305, -0.4287, -0.1051, -1.8061, -0.5696,  2.0598,  0.3050, -0.1690,
         0.5868, -0.2422, -0.6184, -0.8001, -0.4490, -0.2485,  0.5354, -1.5804])

In [41]:
z =x.view(2,8)
z

tensor([[ 0.2305, -0.4287, -0.1051, -1.8061, -0.5696,  2.0598,  0.3050, -0.1690],
        [ 0.5868, -0.2422, -0.6184, -0.8001, -0.4490, -0.2485,  0.5354, -1.5804]])

In [43]:
z = x.view(-1,8)
z

tensor([[ 0.2305, -0.4287, -0.1051, -1.8061, -0.5696,  2.0598,  0.3050, -0.1690],
        [ 0.5868, -0.2422, -0.6184, -0.8001, -0.4490, -0.2485,  0.5354, -1.5804]])

## 与Numpy协同的操作

In [54]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [55]:
a.numpy()

RuntimeError: Numpy is not available

In [56]:
a = np.ones(5)
b = torch.from_numpy(a)
b

RuntimeError: Numpy is not available

注意：这儿不能互相转换是因为版本的不兼容问题

如何学框架，一步一步走，遇到问题再去查找即可，一开始没必要把所有的概念和函数全背下来