In [34]:
import torch,tensorflow
torch.__version__

'1.12.1+cpu'

In [35]:
tensorflow.__version__

'2.9.1'

## 基本使用方法
创建一个矩阵，据说比tensorflow简单很多

In [3]:
x = torch.empty(5,3)
x

C:\Users\84119891\AppData\Local\Temp\ipykernel_3736\3896181131.py:1: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  x = torch.empty(5,3)


tensor([[1.1112e-38, 9.5511e-39, 1.0102e-38],
        [9.9184e-39, 9.0000e-39, 1.0561e-38],
        [1.0653e-38, 4.1327e-39, 8.9082e-39],
        [9.8265e-39, 9.4592e-39, 1.0561e-38],
        [9.8265e-39, 1.0469e-38, 1.0561e-38]])

In [29]:
import numpy as np
import pandas as pd
x_np = np.empty([5,3])
x_np

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
x_np1 = np.zeros([5,3])
x_np1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

来一个随机数来试试水,tensor 是一个张量，二维叫矩阵

In [6]:
x = torch.rand(5,3)
x

tensor([[0.1721, 0.0952, 0.4909],
        [0.4255, 0.8727, 0.8079],
        [0.0387, 0.4829, 0.4437],
        [0.1262, 0.5102, 0.5326],
        [0.3184, 0.1092, 0.7935]])

初始化一个全零的矩阵

In [7]:
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

直接传入数据

In [8]:
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [9]:
x.shape

torch.Size([2])

我们可以感受到，与Numpy的区别并不大，其实这些框架的基本操作都是大同小异的

In [10]:
x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [11]:
x = torch.ones(5,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [12]:
x = torch.randn_like(x,dtype=torch.float)
x

tensor([[-0.0460,  0.4589, -0.4686],
        [ 0.6888, -0.5716,  1.3733],
        [-0.0681, -0.9732, -1.1474],
        [ 1.6698, -0.3053,  0.5039],
        [ 0.8564, -0.8132, -1.0298]])

tensor的大小

In [13]:
x.size()

torch.Size([5, 3])

In [14]:
x.shape

torch.Size([5, 3])

## 基本计算方法

In [15]:
y = torch.rand(5,3)
y

tensor([[0.0416, 0.6816, 0.6987],
        [0.0913, 0.8123, 0.3692],
        [0.8055, 0.4545, 0.5168],
        [0.8488, 0.0664, 0.8789],
        [0.9175, 0.5970, 0.0209]])

In [16]:
x+y

tensor([[-0.0044,  1.1405,  0.2301],
        [ 0.7802,  0.2407,  1.7425],
        [ 0.7374, -0.5187, -0.6306],
        [ 2.5186, -0.2389,  1.3828],
        [ 1.7739, -0.2162, -1.0090]])

In [17]:
torch.add(x,y)## 一样也是加法

tensor([[-0.0044,  1.1405,  0.2301],
        [ 0.7802,  0.2407,  1.7425],
        [ 0.7374, -0.5187, -0.6306],
        [ 2.5186, -0.2389,  1.3828],
        [ 1.7739, -0.2162, -1.0090]])

## 索引

In [18]:
x[:,1]

tensor([ 0.4589, -0.5716, -0.9732, -0.3053, -0.8132])

## view操作可以改变矩阵的维度
可以对比reshape操作

In [19]:
x = torch.randn(4,4)
x

tensor([[-0.6763,  1.2557, -0.1511,  1.4771],
        [ 0.9820, -1.8705, -0.3303,  0.6605],
        [-0.6027,  0.4082,  0.7118,  0.8806],
        [ 0.1281, -0.5332, -0.8583, -1.2869]])

In [20]:
y = x.view(16)
y

tensor([-0.6763,  1.2557, -0.1511,  1.4771,  0.9820, -1.8705, -0.3303,  0.6605,
        -0.6027,  0.4082,  0.7118,  0.8806,  0.1281, -0.5332, -0.8583, -1.2869])

In [21]:
z =x.view(2,8)
z

tensor([[-0.6763,  1.2557, -0.1511,  1.4771,  0.9820, -1.8705, -0.3303,  0.6605],
        [-0.6027,  0.4082,  0.7118,  0.8806,  0.1281, -0.5332, -0.8583, -1.2869]])

In [22]:
z = x.view(-1,8)
z

tensor([[-0.6763,  1.2557, -0.1511,  1.4771,  0.9820, -1.8705, -0.3303,  0.6605],
        [-0.6027,  0.4082,  0.7118,  0.8806,  0.1281, -0.5332, -0.8583, -1.2869]])

## 与Numpy协同的操作

In [23]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [24]:
a.numpy()

RuntimeError: Numpy is not available

In [25]:
a = np.ones(5)
b = torch.from_numpy(a)
b

RuntimeError: Numpy is not available

注意：这儿不能互相转换是因为版本的不兼容问题

如何学框架，一步一步走，遇到问题再去查找即可，一开始没必要把所有的概念和函数全背下来

In [26]:
a = np.ones(5)
b = torch.tensor(a)
b
# array 转 tensor是成功的

tensor([1., 1., 1., 1., 1.])

In [31]:
a = torch.ones(5)
b = np.array(a)
b

RuntimeError: Numpy is not available

In [ ]:
# 你的问题可能在于tensorflow和pytorch版本相差较大，
# 或者你使用torch语句加了.device()语句使加载数据加到了gpu上，但
# 是cpu版本tensorflow产生了限制