In [1]:
import torch,tensorflow
torch.__version__

e:\download\python\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


'1.12.1+cpu'

In [2]:
tensorflow.__version__

'2.9.1'

In [3]:
import numpy
numpy.__version__

'1.23.2'

In [4]:
torch.cuda.is_available

<function torch.cuda.is_available() -> bool>

## 基本使用方法
创建一个矩阵，据说比tensorflow简单很多

In [3]:
x = torch.empty(5,3)
x

tensor([[9.2755e-39, 1.0561e-38, 1.1204e-38],
        [1.1112e-38, 4.2246e-39, 1.0286e-38],
        [1.0653e-38, 1.0194e-38, 8.4490e-39],
        [1.0469e-38, 9.3674e-39, 9.9184e-39],
        [8.7245e-39, 9.2755e-39, 8.9082e-39]])

In [4]:
import numpy as np
import pandas as pd
x_np = np.empty([5,3])
x_np

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
x_np1 = np.zeros([5,3])
x_np1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

来一个随机数来试试水,tensor 是一个张量，二维叫矩阵

In [6]:
x = torch.rand(5,3)
x

tensor([[0.4950, 0.3780, 0.7198],
        [0.0209, 0.3861, 0.5043],
        [0.1172, 0.0420, 0.6842],
        [0.0151, 0.4016, 0.2318],
        [0.1268, 0.6223, 0.7810]])

初始化一个全零的矩阵

In [7]:
x = torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

直接传入数据

In [8]:
x = torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [9]:
x.shape

torch.Size([2])

我们可以感受到，与Numpy的区别并不大，其实这些框架的基本操作都是大同小异的

In [10]:
x = x.new_ones(5,3,dtype=torch.double)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [11]:
x = torch.ones(5,3)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [12]:
x = torch.randn_like(x,dtype=torch.float)
x

tensor([[ 0.8076,  0.1542, -0.4286],
        [-0.1506,  0.3665,  0.3166],
        [-0.1741,  0.2147,  0.3629],
        [ 0.1674,  1.5266,  1.6677],
        [ 0.1600, -0.8122,  1.1214]])

tensor的大小

In [13]:
x.size()

torch.Size([5, 3])

In [14]:
x.shape

torch.Size([5, 3])

## 基本计算方法

In [15]:
y = torch.rand(5,3)
y

tensor([[0.1421, 0.8568, 0.7727],
        [0.9555, 0.8240, 0.9683],
        [0.9800, 0.5214, 0.6705],
        [0.4044, 0.1889, 0.7243],
        [0.5365, 0.8495, 0.2271]])

In [16]:
x+y

tensor([[0.9498, 1.0111, 0.3441],
        [0.8049, 1.1905, 1.2849],
        [0.8059, 0.7361, 1.0335],
        [0.5718, 1.7155, 2.3920],
        [0.6965, 0.0373, 1.3485]])

In [17]:
torch.add(x,y)## 一样也是加法

tensor([[0.9498, 1.0111, 0.3441],
        [0.8049, 1.1905, 1.2849],
        [0.8059, 0.7361, 1.0335],
        [0.5718, 1.7155, 2.3920],
        [0.6965, 0.0373, 1.3485]])

## 索引

In [18]:
x[:,1]

tensor([ 0.1542,  0.3665,  0.2147,  1.5266, -0.8122])

## view操作可以改变矩阵的维度
可以对比reshape操作

In [19]:
x = torch.randn(4,4)
x

tensor([[-0.1706,  0.2072,  0.1413, -0.2364],
        [-0.6516,  1.4303,  0.5397, -1.1042],
        [-1.3097,  1.1500,  0.2241, -0.2323],
        [ 0.9095, -0.1992, -0.0614, -0.5345]])

In [20]:
y = x.view(16)
y

tensor([-0.1706,  0.2072,  0.1413, -0.2364, -0.6516,  1.4303,  0.5397, -1.1042,
        -1.3097,  1.1500,  0.2241, -0.2323,  0.9095, -0.1992, -0.0614, -0.5345])

In [21]:
z =x.view(2,8)
z

tensor([[-0.1706,  0.2072,  0.1413, -0.2364, -0.6516,  1.4303,  0.5397, -1.1042],
        [-1.3097,  1.1500,  0.2241, -0.2323,  0.9095, -0.1992, -0.0614, -0.5345]])

In [22]:
z = x.view(-1,8)
z

tensor([[-0.1706,  0.2072,  0.1413, -0.2364, -0.6516,  1.4303,  0.5397, -1.1042],
        [-1.3097,  1.1500,  0.2241, -0.2323,  0.9095, -0.1992, -0.0614, -0.5345]])

## 与Numpy协同的操作

In [23]:
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [24]:
a.numpy()

array([1., 1., 1., 1., 1.], dtype=float32)

In [25]:
a = np.ones(5)
b = torch.from_numpy(a)
b

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

注意：这儿不能互相转换是因为版本的不兼容问题

如何学框架，一步一步走，遇到问题再去查找即可，一开始没必要把所有的概念和函数全背下来

In [26]:
a = np.ones(5)
b = torch.tensor(a)
b
# array 转 tensor是成功的

tensor([1., 1., 1., 1., 1.])

In [26]:
a = torch.ones(5)
b = np.array(a)
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [ ]:
# 你的问题可能在于tensorflow和pytorch版本相差较大，
# 或者你使用torch语句加了.device()语句使加载数据加到了gpu上，但
# 是cpu版本tensorflow产生了限制