In [20]:
import torch

## 框架真正厉害的点？
可以帮我们把反向传播全部计算好

In [21]:
# Method 1 - recommended
x = torch.randn(3,4,requires_grad=True)
x

tensor([[ 1.0264, -0.3336,  1.2340,  0.7088],
        [-0.6084,  0.9388, -0.4922,  0.0050],
        [-0.0308, -0.3945, -1.1966,  0.0087]], requires_grad=True)

In [22]:
# Method 2
x = torch.randn(3,4)
x.requires_grad = True
x

tensor([[ 0.3705, -0.2516,  1.0966, -0.6605],
        [ 0.9128,  0.8298,  1.6777,  0.6767],
        [ 0.2689,  0.1837,  0.6901,  0.9913]], requires_grad=True)

In [23]:
b = torch.randn(3,4,requires_grad=True)
b

tensor([[-1.6648, -0.7245, -0.5792,  0.6969],
        [-0.9014,  0.7183, -1.4697,  1.0863],
        [ 0.8653,  0.1859,  0.4625,  0.0201]], requires_grad=True)

In [24]:
t = x+b
t

tensor([[-1.2943, -0.9761,  0.5174,  0.0364],
        [ 0.0114,  1.5481,  0.2080,  1.7631],
        [ 1.1342,  0.3695,  1.1526,  1.0114]], grad_fn=<AddBackward0>)

In [25]:
y = t.sum()
y

tensor(5.4817, grad_fn=<SumBackward0>)

In [26]:
y.backward()
y

tensor(5.4817, grad_fn=<SumBackward0>)

In [27]:
b.grad
## 这儿的变量就是b，一元一次函数求导

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

虽然没有指定t的required_grad但是需要用到它，也会默认的

In [28]:
x.requires_grad,b.requires_grad,t.requires_grad

(True, True, True)

In [29]:
# calculate flow - example 
x = torch.rand(1)
y = torch.rand(1)
w = torch.rand(1,requires_grad=True)
y = w*x
z = y+b

In [30]:
# check autograde
x.requires_grad,b.requires_grad,w.requires_grad

(False, True, True)

In [40]:
## again
x = torch.rand(1)
b = torch.rand(1,requires_grad=True)
w = torch.rand(1,requires_grad=True)
y = w*x
z = y+b

In [36]:
# check autograde
x.requires_grad,b.requires_grad,w.requires_grad,y.requires_grad # y is needed

(False, True, True, True)

In [32]:
x.is_leaf,w.is_leaf,b.is_leaf,y.is_leaf,z.is_leaf
# z = wx+b,是否为叶子结点

(True, True, True, False, False)

In [41]:
# back propagation
z.backward(retain_graph=True) # 注意，如果不清空梯度会累加起来


In [42]:
w.grad

tensor([0.6417])

In [43]:
b.grad

tensor([1.])

线性回归试水

In [46]:
# 构造一组输入数据X与对应的标签Y
import numpy as np
x_values = [i for i in range(11)]
x_train  = np.array(x_values,dtype = np.float32)
x_train = x_train.reshape(-1,1)
x_train.shape

(11, 1)

In [49]:
import numpy as np
y_values = [2*i+1 for i in range(11)]
y_train = np.array(y_values,dtype=np.float32)
y_train = y_train.reshape(-1,1)
y_train.shape

(11, 1)

In [50]:
import torch 
import torch.nn as nn

线性回归模型

In [ ]:
# 线性回归就是不添加激活函数的全连接层
class LinearRegressionModel(nn.Module):
    def __init__(self,input_dim,output_dim):
        super(LinearRegressionModel,self).__init__()
        self.linear = nn.Linear(input_dim,output_dim)
