In [1]:
import torch

## 框架真正厉害的点？
可以帮我们把反向传播全部计算好

In [2]:
# Method 1
x = torch.randn(3,4,requires_grad=True)
x

C:\Users\84119891\AppData\Local\Temp\ipykernel_24920\2897918177.py:2: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of numpy is 0xf (Triggered internally at  ..\torch\csrc\utils\tensor_numpy.cpp:68.)
  x = torch.randn(3,4,requires_grad=True)


tensor([[-1.3314, -0.3811, -0.0295, -0.5791],
        [ 2.6213, -0.8445,  0.3071, -1.5502],
        [ 0.9177,  1.4740, -0.8213,  0.6599]], requires_grad=True)

In [3]:
# Method 2
x = torch.randn(3,4)
x.requires_grad = True
x

tensor([[ 0.6583, -0.9826,  0.3658,  0.5011],
        [-2.0702,  1.3061,  1.6431, -0.1624],
        [-0.6627, -2.1044,  1.6941,  0.4143]], requires_grad=True)

In [10]:
b = torch.randn(3,4,requires_grad=True)
b

tensor([[ 1.2318,  0.3051, -2.4395,  0.0179],
        [-0.7601, -0.9199, -0.1384,  1.0214],
        [ 0.2637,  0.7955,  0.6287,  0.1540]], requires_grad=True)

In [11]:
t = x+b
t

tensor([[ 1.8901, -0.6776, -2.0737,  0.5190],
        [-2.8303,  0.3862,  1.5047,  0.8590],
        [-0.3990, -1.3089,  2.3228,  0.5683]], grad_fn=<AddBackward0>)

In [12]:
y = t.sum()
y

tensor(0.7606, grad_fn=<SumBackward0>)

In [15]:
y.backward()
y

tensor(0.7606, grad_fn=<SumBackward0>)

In [16]:
b.grad

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])