# Tensor常见的形式有哪些
- 0:sccalar
- 1:vector
- 2:matrix
- 3:n-dimensional tensor



In [3]:
import torch
from torch import tensor

Scalar 通常是一个数值

In [4]:
x = tensor(43,)
x

tensor(43)

In [5]:
x.dim()

0

In [6]:
x.item()

43

Vector 在深度学习中通常表示特征：身高体重年龄

In [7]:
v= tensor([1.5,-0.5,3.0])
v

tensor([ 1.5000, -0.5000,  3.0000])

In [8]:
v.dim()

1

In [10]:
v.size()

torch.Size([3])

Matrix: 张三李四王五的特征的组合

In [12]:
M = tensor([[1.,2.],[3.,4.]])
M

tensor([[1., 2.],
        [3., 4.]])

In [13]:
M.matmul(M)

tensor([[ 7., 10.],
        [15., 22.]])

In [15]:
tensor([1.,0.]).matmul(M)

tensor([1., 2.])

In [16]:
M*M

tensor([[ 1.,  4.],
        [ 9., 16.]])

# 强大的HUB模块
调用别人训练好的网络架构以及训练好的权重参数，方便懒人调用

In [ ]:
## github: https://github.com/pytorch/hub
## models:https://github.org/hub/research-models
# import torch
# model = torch.hub.load()